import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import tsconfigPaths from 'vite-tsconfig-paths';

// SPA build for Docker/nginx deployment.
// Does NOT use TanStack Start or Cloudflare plugins — pure client-side React.
// routeTree.gen.ts must already exist (generated by the normal dev/build workflow).
export default defineConfig({
  plugins: [react(), tailwindcss(), tsconfigPaths()],
  build: {
    outDir: 'dist/spa',
    emptyOutDir: true,
  },
});
